#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &
xset s off
xset -dpms
xsetroot -cursor_name left_ptr
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config single_monocle		  true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color           "#44475A"
bspc config focused_border_color          "#BD93F9"

bspc rule -a Hudkit border=off
bspc rule -a hudkit border=off
bspc rule -a parser border=off
bspc rule -a cactbot border=off
bspc rule -a 'steam_proton:advanced combat tracker.exe' desktop=X

run_startup() {
	if [ -z "$2" ]; then
		pgrep -x "$1" > /dev/null || $1 &
		return 1;
	fi
	
	pgrep -x "$1" > /dev/null || $2 &
	return 2;
}

run_startup "polybar" "polybar -r aneko"

# Compositor
run_startup "picom"

# udiskie
run_startup "udiskie" "udiskie --tray"

# fcitx
run_startup "fcitx"

# unclutter
run_startup "unclutter"

# ckb-next
run_startup "ckb-next" "ckb-next --background"

# nm-applet
run_startup "nm-applet"

# polkit
run_startup "lxpolkit"

# light locker
run_startup "light-locker"
